
-define(MAX_FIGHT_NUM, 512).
-define(FIRST_EIGHT, 8).
-define(FIRST_FOUR, 4).
-define(FIRST_TWO, 2).
-define(FIRST_ONE, 1).

%% 跨服战活动的状态
-define(STATUS_NOT_OPEN,            0).
-define(STATUS_WAIT_SIGN,           1).
-define(STATUS_SIGN,                2).
-define(STATUS_WAIT_PRE_FIHGT,      3).
-define(STATUS_PRE_FIGHT,           4). 
-define(STATUS_WAIT_EIGHT_FIGHT,    5).
-define(STATUS_EIGHT_FIGHT,         6). 
-define(STATUS_WAIT_FOUR_FIGHT,     7).
-define(STATUS_FOUR_FIGHT,          8).      
-define(STATUS_WAIT_TWO_FIGHT,      9).
-define(STATUS_TWO_FIGHT,           10).
-define(STATUS_WAIT_FINAL_FIGHT,    11).
-define(STATUS_FINAL_FIGHT,         12).


%% 错误返回提示码
-define(REASON_CODE_NOT_SLAVE_SERVER_CAN_NOT_SIGN, 1).
-define(REASON_CODE_NOT_SIGN_TIME, 2).
-define(REASON_CODE_ROLE_LEVEL_NOT_ENOUGH, 3).
-define(REASON_CODE_ROLE_ALREADY_SIGN, 4).
-define(REASON_CODE_SIGN_NUM_IS_MAX, 5).
-define(REASON_CODE_LOCAL_CROSS_SERVER_IS_DOWN, 6).
-define(REASON_CODE_CAN_NOT_GET_ROLE_INFO, 7).
-define(REASON_CODE_SIGN_FAIL_CROSS_MASTER_DOWN, 8).

-define(REASON_CODE_ALREADY_SUPPORT_SKY, 1).
-define(REASON_CODE_ALREADY_SUPPORT_GROUND, 2).
-define(REASON_CODE_SUPPORT_ROLE_NOT_EXIST, 3).
-define(REASON_CODE_SUPPORT_FAIL_ROLE_COIN_NOT_ENOUGH, 4).
-define(REASON_CODE_SUPPORT_FAIL_LOCAL_CROSS_SERVER_DOWN, 5).
-define(REASON_CODE_SUPPORT_FAIL_MASTER_CROSS_SERVER_DOWN, 6).
-define(REASON_CODE_SUPPORT_FAIL_CONFIG_ERROR, 7).
-define(REASON_CODE_SUPPORT_FAIL_SUPPORT_ROLE_ID_NOT_IN_SPEC_LIST, 8).
-define(REASON_CODE_SUPPORT_FAIL_NOW_STATUS_CAN_NOT_SUPPORT, 9).

%% 榜单类型
-define(LAST_SKY_LIST, 0).
-define(LAST_GROUND_LIST, 1).
-define(NOW_SKY_LIST, 2).
-define(NOW_GROUND_LIST, 3).

-define(CHANNEL_SKY, 0).
-define(CHANNEL_GROUND, 1).

-define(PRICE_LIST_SKY, 0).
-define(PRICE_LIST_GROUND, 1).

-define(SUPPORT_SKY, 0).
-define(SUPPORT_GROUND, 1).

-define(HISTORY_TYPE_NORMAL, 0).
-define(HISTORY_TYPE_SKY, 1).
-define(HISTORY_TYPE_GROUND, 2).


